ecommerce:
  target: dev_core
  outputs:

    dev_core: 
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      schema: analytics_core
      threads: 4

    dev_fusion:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      schema: analytics_fusion
      threads: 4

    # dev_core_pg:
    #   type: postgres
    #   host: "{{ env_var('POSTGRES_HOST') }}"
    #   port: "{{ env_var('POSTGRES_PORT') | int }}"
    #   user: "{{ env_var('POSTGRES_USER') }}"
    #   password: "{{ env_var('POSTGRES_PASSWORD') }}"
    #   dbname: "{{ env_var('POSTGRES_DB') }}"
    #   schema: analytics_core
    #   threads: 4
    
    # dev_fusion_pg:
    #   type: postgres
    #   host: "{{ env_var('POSTGRES_HOST') }}"
    #   port: "{{ env_var('POSTGRES_PORT') | int }}"
    #   user: "{{ env_var('POSTGRES_USER') }}"
    #   password: "{{ env_var('POSTGRES_PASSWORD') }}"
    #   dbname: "{{ env_var('POSTGRES_DB') }}"
    #   schema: analytics_fusion
    #   threads: 4
    
  vars:
    DBT_ALLOW_EXPERIMENTAL_ADAPTERS: true