ecommerce:
  target: dev_core
  outputs:
    dev_core: 
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      schema: analytics_core
      threads: 4
    dev_fusion:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      schema: analytics_fusion
      threads: 4
  vars:
    DBT_ALLOW_EXPERIMENTAL_ADAPTERS: true